# Generated by Django 3.2 on 2021-08-06 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title field can not be blank.', max_length=300)),
                ('company', models.CharField(help_text='Company field can not be blank.', max_length=300)),
                ('job_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], help_text='Select a type of job!', max_length=20)),
                ('location', models.CharField(help_text='Example: City, Provice, Country.', max_length=200)),
                ('description', models.TextField(default=None, help_text='Can not be blank. Describe about the job.')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now, help_text='By default time added, but you can edit it.')),
                ('slug', models.SlugField(default=None, editable=False, help_text='This field will automatically be fullfielded.')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Select the status.', max_length=10)),
                ('employer', models.ForeignKey(help_text='Select an employer.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ('-publishing_date',),
            },
        ),
    ]
