# Generated by Django 3.2 on 2021-08-06 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title field can NOT blank.', max_length=300)),
                ('company', models.CharField(help_text='Company field can NOT blank.', max_length=300)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], help_text='Select a type of job!', max_length=20)),
                ('location', models.CharField(help_text='Example: City, Provice, Country.', max_length=200)),
                ('description', models.TextField(default=None, help_text='Can not blank. Describe about the job.')),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, editable=False, help_text='This field will automatically be fullfielded.')),
                ('employer', models.ForeignKey(help_text='Employer field.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ('-id',),
            },
        ),
    ]
