# Generated by Django 3.2 on 2021-08-06 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(help_text='Company field can not be blank.', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=None, help_text='Can not be blank. Describe about the job.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], help_text='Select a type of job!', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='publishing_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='By default time added, but you can edit it.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Title field can not be blank.', max_length=300),
        ),
    ]
